### ISSUE TITLE
Bug in Subfigure Format

### ISSUE THREAD

**Issue by rbreslavsky** [nasa/cape#10]
Unsure if this is a bug or intended behavior, but when indicating `"Format": png` for a subfigure, subfigure png files are created in addition to (not instead of) pdf files.

The resultant report is made of vector images rather than raster images.

**Comment by nasa-ddalle** [comment]
Altered this behavior in commit `67ecf616`.

Now, if you use `"Format": "png"` (or `"Format": "jpg"`), it should just create one file and include the rasterized fig in the PDF. This was originally intended behavior with the mindset that "vector images are always better" alongside "users might want a rasterized image to use in other formats (e.g. HTML)". There's still a check for the case where you put `"Format": "svg"`, which LaTeX can't handle (at least not normally.... that could probably be done, too), in which case CAPE spits out an `.svg` and `.pdf` to use in the report still. But now it'll just assume if you give it anything else, you really meant it, and don't create the PDF as an alternate.
