### ISSUE TITLE
Feature Request: Reports

### ISSUE THREAD

**Issue by rbreslavsky** [nasa/cape#11]
Would like to request some features regarding reports:

1. Command line option to clear a case report folder
2. Command line option to force an update to a case report folder, even if images are assumed to be current
3. Command line option to update case report folders without propagating their contents into a compiled final report

**Comment by nasa-ddalle** [comment]
Ok, we've just added the following CLI extras in relation to this issue:

```
    --report RP --force
        Update report and ignore cache for all subfigures

    --report RP --no-compile
        Create images for a report but don't compile into PDF

    --report RP --rm
        Delete existing caches of report subfigure images instead of
        creating them
```

Added in https://github.com/nasa/cape/commit/7d2cb7cb8b60e6339144324b81bfb169cafe8c18

**Comment by rbreslavsky** [comment]
Nice, thank you!
