### ISSUE TITLE
Feature Request: LaTeX Unknown Graphics Extension

### ISSUE THREAD

**Issue by rbreslavsky** [nasa/cape#12]
When generating a report, LaTeX does not look for the last period/dot when looking for an image file extension. For instance, image1.png would be processed normally as a ".png" file, but image.1.png would be assessed as a ".1.png" file, resulting in a LaTeX error. 

To allow for more user flexibility, could we consider a switch from the _graphicx_ package to _grffile_?

https://tex.stackexchange.com/questions/110513/unknown-graphics-extension-1-png

**Comment by nasa-ddalle** [comment]
Does *grffile* require any other changes for compatibility? It sounds like that could be pretty easy as long as most people are likely to have *grffile*.

**Comment by rbreslavsky** [comment]
Actually, looking at this more closely, the problems I was having could simply be due to an old version of _texliv_. _grffile_ was a workaround a few years back, but may no longer be needed. Let's hold off on any implementation until I have time to try this with a newer version of _texliv_.

**Comment by rbreslavsky** [comment]
I think we can close this for now.
