### ISSUE TITLE
Let Slurm determine the number of cores for mpiexec

### ISSUE THREAD

**Issue by mlong-vg** [nasa/cape#15]
If the MPI library used to build FUN3D has proper Slurm integration then it should be possible to execute the solver without specifying the number of cores/procs in the mpiexec launch command.  We typically launch jobs with just the -N and --ntasks-per-node options to Slurm, which avoids having to do the math for how many total cores are being requested.

Maybe an option in pyFun.json where setting "nProc" to -1 removes the -n {nProc} part of the mpiexec command?

Not sure if that would work with the other solvers but it should since it's dealing with the MPI library.

**Comment by nasa-ddalle** [comment]
This will be easy to integrate, and a similar thing might be possible in PBS too (except that maybe CAPE determines it manually). We have had cases where using less than the obvious max for `"nProc"` was necessary, but that's not going to get in the way of your suggestion.

**Comment by nasa-ddalle** [comment]
I think `2df277b1` should take care of this. You can use any negative, `0`, or `null` value for `"nProc"` and then it will just run `mpiexec nodet_mpi`.
