### ISSUE TITLE
Feature request: Add axis limits to iteration histories

### ISSUE THREAD

**Issue by rbreslavsky** [nasa/cape#17]
Currently, it doesn't seem as if iteration history plots can use axis limit keyword arguments such as 'XLim' and 'YLim'. This can be problematic if a transient spike causes the axes to auto scale to large values.

**Comment by nasa-ddalle** [comment]
I've added several options for `"PlotCoeff"` subfigures:

* `"YLim"`: list of explicit min and explicit max to use for *y*-axis
* `"YMin"`: explicit min to use for *y*-axis
* `"YMax"`: explicit max to use for *y*-axis
* `"YLimMax"`: outer bounds for *ymin* and *ymax*; CAPE will not plot a *y*-value below ``YLimMax[0]`` but may have a min *y*-axis value greater than that, and CAPE will not plot a *y*-value above ``YLimMax[1]``. Also supports using ``None`` (in Python) or ``null`` (in JSON) to use one of the bounds. E.g. ``"YLimMax": [0.0, null]`` will guarantee only positive *y*-values are shown but not set an upper bound.
* same options, replacing ``Y`` -> ``X``
