### ISSUE TITLE
CAPE resubmits case even when cases has failed with nan*.dat

### ISSUE THREAD

**Issue by khalilsb** [nasa/cape#23]
When running fun3d cases with two phases, if the solver diverges on the 2nd phase cape will try to resubmit that case. This creates an endless loop where it will keep resubmitting until the case is manually killed. Does cape not look for nan*dat files

**Comment by nasa-ddalle** [comment]
pyfun looks for `nan_locations*.dat`, which you can see in `cape/pyfun/cntl.py`. If you're using the `v1.1` branch, it's possible that there was a bug created during the upgrade. Is there another kind of `nan*.dat` file that FUN3D can create?

**Comment by nasa-ddalle** [comment]
I'm looking at the `cape.pyfun.case` source code and seeing there might have been a long-time bug. Possibly it's only doing that check during a resubmit. The case should show as `ERROR` for `pyfun -c`, right?

**Comment by nasa-ddalle** [comment]
Could see some improvement from https://github.com/nasa/cape/commit/b20755d215d0bc16d56895b7a9d8c61eab00330b

Actually on leave this week, so a bit of a quick fix ...

**Comment by khalilsb** [comment]
thanks for the quick reply! Yup i was referring to the nan_locations*dat files. correct if it does that check during a resubmit it catches it and shows ERROR. I'll give that commit a try!
