### ISSUE TITLE
Drag Coefficient

### ISSUE THREAD

**Issue by CarterTegen** [nasa/cape#25]
I'm using PyCart to create carpet plots of cape runs. The CN and CA data all looks good and follows expected trends. Plotting the drag polar in excel using the axes transformations found [here](https://aerospaceweb.org/question/aerodynamics/q0194.shtml) works well and yield proper drag curve with alpha. However, when plotting the sweep using pycart's "CD" coefficient, the CD doesn't match up. The issue makes it seem like the CN term in the CD formulation is negative when it should be positive. Is there a way I can check the formulation of CD for this and make sure it's correct for my axes definition?

**Comment by nasa-ddalle** [comment]
Sorry for the slow response! Yes, you're right, and this was happening in `cape/cfdx/dataBook.py`. You can just search for `CD` in there to find the error, but I've fixed it on all three main branches now.
