### ISSUE TITLE
Bug in set_nMin method of the DataBook module

### ISSUE THREAD

**Issue by vcoralic** [nasa/cape#3]
In v1.0.0rc2, there's a bug in the `set_nMin` method of the `DataBook` module. `set_nMin` has `nMin` as an input, but uses `nStats` instead, which is not in the namespace of the method and leads to `NameError: name 'nStats' is not defined`. I expect it should be `self['nMin'] = nMin` instead of `self['nMin'] = nStats` on line 427.

**Comment by nasa-ddalle** [comment]
Fixed in `72e184f8`, as suggested.
