### ISSUE TITLE
No Symmetry Volume Mesh Option in AutoInputs

### ISSUE THREAD

**Issue by aylee7** [nasa/cape#31]
When using CART3D without CAPE, I can specify autoInputs -halfbody -symmY to generate a volume mesh on only one side of a half body model, but no option for this exists in CAPE.

**Comment by nasa-ddalle** [comment]
Ok, I've added it to all three branches (I hope this is the last time I add an option to the `v1.0` branch!) but haven't functionally tested it. Looks like it's actually `-halfBody`, but I added `halfbody=True` as a valid alias (for `v1.1` and `main`) in the `"RunControl"` > `"autoInputs"` section.

**Comment by aylee7** [comment]
Thanks so much!
