### ISSUE TITLE
Add Arbitrary Slurm Instructions

### ISSUE THREAD

**Issue by rbreslavsky** [nasa/cape#32]
In CAPE, we can add Slurm options via `opts["Slurm"]["other"]`, but it has to be a dictionary. So, for instance, `opts["Slurm"]["other"] = {"export": "ALL"}` writes out `#SBATCH --export=ALL` in the submission script.

But what if we want something without the equals sign? Like `#SBATCH --exclusive`?

**Comment by nasa-ddalle** [comment]
Ok, so for that you can put (after the commit I just pushed to both `v1.1` and `main`)

```python
opts["Slurm"]["other"] = {"exclusive": True}
```

or, in JSON

```javascript
"Slurm": {
    "other": {
        "exclusive": true
    }
}
```

I should not have missed this in my initial `"Slurm"` > `"other"` implementation!
