### ISSUE TITLE
Bug: FUN3D Line Load Generation Fails When `boundary_animation_freq = -1`

### ISSUE THREAD

**Issue by vcoralic** [nasa/cape#7]
CAPE does not correctly treat the corner case where boundary variables are only outputted at the end of a simulation. Specifically, when `boundary_animation_freq = -1`,  FUN3D outputs the following boundary file name pattern, `fglb = '%s_tec_boundary.plt' % proj`, but CAPE still looks for `fglb = '%s_tec_boundary_timestep[1-9]*.plt' % proj` (see line 326 of pyfun/lineLoad.py).

On a related note, the failure mode when FUN3D is unable to find the relevant `*.plt` file is somewhat cryptic: `“Not enough iterations (None) for analysis”`. It might be a good idea to catch this particular failure mode more explicitly, *i.e.*, by printing to screen that the required file(s) could not be found.

**Comment by nasa-ddalle** [comment]
Fixed in `ef07fdf`. Slightly painful that FUN3D did this to us! Thanks for finding that; we were planning to change our operations to use `boundary_animation_freq = -1` for our next runs, too.
